using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FractalExplorer.Rendering;

namespace FractalExplorer {
	public static class RendererUtils {
		public static void FillRectangle (int pixelValue, int width, uint iter, uint color) {
			try {
				switch (Renderer.renderStage) {
				case 0:
					Renderer.pixels[pixelValue] = color;
					Renderer.iterations[pixelValue] = iter;
					break;
				case 1:
					Renderer.pixels[pixelValue] = color;
					Renderer.pixels[pixelValue + 1] = color;

					Renderer.pixels[pixelValue + width] = color;
					Renderer.pixels[pixelValue + width + 1] = color;

					Renderer.iterations[pixelValue] = iter;
					Renderer.iterations[pixelValue + 1] = iter;

					Renderer.iterations[pixelValue + width] = iter;
					Renderer.iterations[pixelValue + width + 1] = iter;
					break;
				case 2:
					Renderer.pixels[pixelValue] = color;
					Renderer.pixels[pixelValue + 1] = color;
					Renderer.pixels[pixelValue + 2] = color;
					Renderer.pixels[pixelValue + 3] = color;

					Renderer.pixels[pixelValue + width] = color;
					Renderer.pixels[pixelValue + width + 1] = color;
					Renderer.pixels[pixelValue + width + 2] = color;
					Renderer.pixels[pixelValue + width + 3] = color;

					Renderer.pixels[pixelValue + 2 * width] = color;
					Renderer.pixels[pixelValue + 2 * width + 1] = color;
					Renderer.pixels[pixelValue + 2 * width + 2] = color;
					Renderer.pixels[pixelValue + 2 * width + 3] = color;

					Renderer.pixels[pixelValue + 3 * width] = color;
					Renderer.pixels[pixelValue + 3 * width + 1] = color;
					Renderer.pixels[pixelValue + 3 * width + 2] = color;
					Renderer.pixels[pixelValue + 3 * width + 3] = color;

					Renderer.iterations[pixelValue] = iter;
					Renderer.iterations[pixelValue + 1] = iter;
					Renderer.iterations[pixelValue + 2] = iter;
					Renderer.iterations[pixelValue + 3] = iter;

					Renderer.iterations[pixelValue + width] = iter;
					Renderer.iterations[pixelValue + width + 1] = iter;
					Renderer.iterations[pixelValue + width + 2] = iter;
					Renderer.iterations[pixelValue + width + 3] = iter;

					Renderer.iterations[pixelValue + 2 * width] = iter;
					Renderer.iterations[pixelValue + 2 * width + 1] = iter;
					Renderer.iterations[pixelValue + 2 * width + 2] = iter;
					Renderer.iterations[pixelValue + 2 * width + 3] = iter;

					Renderer.iterations[pixelValue + 3 * width] = iter;
					Renderer.iterations[pixelValue + 3 * width + 1] = iter;
					Renderer.iterations[pixelValue + 3 * width + 2] = iter;
					Renderer.iterations[pixelValue + 3 * width + 3] = iter;
					break;
				case 3:
					Renderer.pixels[pixelValue] = color;
					Renderer.pixels[pixelValue + 1] = color;
					Renderer.pixels[pixelValue + 2] = color;
					Renderer.pixels[pixelValue + 3] = color;
					Renderer.pixels[pixelValue + 4] = color;
					Renderer.pixels[pixelValue + 5] = color;
					Renderer.pixels[pixelValue + 6] = color;
					Renderer.pixels[pixelValue + 7] = color;

					Renderer.pixels[pixelValue + width] = color;
					Renderer.pixels[pixelValue + width + 1] = color;
					Renderer.pixels[pixelValue + width + 2] = color;
					Renderer.pixels[pixelValue + width + 3] = color;
					Renderer.pixels[pixelValue + width + 4] = color;
					Renderer.pixels[pixelValue + width + 5] = color;
					Renderer.pixels[pixelValue + width + 6] = color;
					Renderer.pixels[pixelValue + width + 7] = color;

					Renderer.pixels[pixelValue + 2 * width] = color;
					Renderer.pixels[pixelValue + 2 * width + 1] = color;
					Renderer.pixels[pixelValue + 2 * width + 2] = color;
					Renderer.pixels[pixelValue + 2 * width + 3] = color;
					Renderer.pixels[pixelValue + 2 * width + 4] = color;
					Renderer.pixels[pixelValue + 2 * width + 5] = color;
					Renderer.pixels[pixelValue + 2 * width + 6] = color;
					Renderer.pixels[pixelValue + 2 * width + 7] = color;

					Renderer.pixels[pixelValue + 3 * width] = color;
					Renderer.pixels[pixelValue + 3 * width + 1] = color;
					Renderer.pixels[pixelValue + 3 * width + 2] = color;
					Renderer.pixels[pixelValue + 3 * width + 3] = color;
					Renderer.pixels[pixelValue + 3 * width + 4] = color;
					Renderer.pixels[pixelValue + 3 * width + 5] = color;
					Renderer.pixels[pixelValue + 3 * width + 6] = color;
					Renderer.pixels[pixelValue + 3 * width + 7] = color;

					Renderer.pixels[pixelValue + 4 * width] = color;
					Renderer.pixels[pixelValue + 4 * width + 1] = color;
					Renderer.pixels[pixelValue + 4 * width + 2] = color;
					Renderer.pixels[pixelValue + 4 * width + 3] = color;
					Renderer.pixels[pixelValue + 4 * width + 4] = color;
					Renderer.pixels[pixelValue + 4 * width + 5] = color;
					Renderer.pixels[pixelValue + 4 * width + 6] = color;
					Renderer.pixels[pixelValue + 4 * width + 7] = color;

					Renderer.pixels[pixelValue + 5 * width] = color;
					Renderer.pixels[pixelValue + 5 * width + 1] = color;
					Renderer.pixels[pixelValue + 5 * width + 2] = color;
					Renderer.pixels[pixelValue + 5 * width + 3] = color;
					Renderer.pixels[pixelValue + 5 * width + 4] = color;
					Renderer.pixels[pixelValue + 5 * width + 5] = color;
					Renderer.pixels[pixelValue + 5 * width + 6] = color;
					Renderer.pixels[pixelValue + 5 * width + 7] = color;

					Renderer.pixels[pixelValue + 6 * width] = color;
					Renderer.pixels[pixelValue + 6 * width + 1] = color;
					Renderer.pixels[pixelValue + 6 * width + 2] = color;
					Renderer.pixels[pixelValue + 6 * width + 3] = color;
					Renderer.pixels[pixelValue + 6 * width + 4] = color;
					Renderer.pixels[pixelValue + 6 * width + 5] = color;
					Renderer.pixels[pixelValue + 6 * width + 6] = color;
					Renderer.pixels[pixelValue + 6 * width + 7] = color;

					Renderer.pixels[pixelValue + 7 * width] = color;
					Renderer.pixels[pixelValue + 7 * width + 1] = color;
					Renderer.pixels[pixelValue + 7 * width + 2] = color;
					Renderer.pixels[pixelValue + 7 * width + 3] = color;
					Renderer.pixels[pixelValue + 7 * width + 4] = color;
					Renderer.pixels[pixelValue + 7 * width + 5] = color;
					Renderer.pixels[pixelValue + 7 * width + 6] = color;
					Renderer.pixels[pixelValue + 7 * width + 7] = color;

					Renderer.iterations[pixelValue] = iter;
					Renderer.iterations[pixelValue + 1] = iter;
					Renderer.iterations[pixelValue + 2] = iter;
					Renderer.iterations[pixelValue + 3] = iter;
					Renderer.iterations[pixelValue + 4] = iter;
					Renderer.iterations[pixelValue + 5] = iter;
					Renderer.iterations[pixelValue + 6] = iter;
					Renderer.iterations[pixelValue + 7] = iter;

					Renderer.iterations[pixelValue + width] = iter;
					Renderer.iterations[pixelValue + width + 1] = iter;
					Renderer.iterations[pixelValue + width + 2] = iter;
					Renderer.iterations[pixelValue + width + 3] = iter;
					Renderer.iterations[pixelValue + width + 4] = iter;
					Renderer.iterations[pixelValue + width + 5] = iter;
					Renderer.iterations[pixelValue + width + 6] = iter;
					Renderer.iterations[pixelValue + width + 7] = iter;

					Renderer.iterations[pixelValue + 2 * width] = iter;
					Renderer.iterations[pixelValue + 2 * width + 1] = iter;
					Renderer.iterations[pixelValue + 2 * width + 2] = iter;
					Renderer.iterations[pixelValue + 2 * width + 3] = iter;
					Renderer.iterations[pixelValue + 2 * width + 4] = iter;
					Renderer.iterations[pixelValue + 2 * width + 5] = iter;
					Renderer.iterations[pixelValue + 2 * width + 6] = iter;
					Renderer.iterations[pixelValue + 2 * width + 7] = iter;

					Renderer.iterations[pixelValue + 3 * width] = iter;
					Renderer.iterations[pixelValue + 3 * width + 1] = iter;
					Renderer.iterations[pixelValue + 3 * width + 2] = iter;
					Renderer.iterations[pixelValue + 3 * width + 3] = iter;
					Renderer.iterations[pixelValue + 3 * width + 4] = iter;
					Renderer.iterations[pixelValue + 3 * width + 5] = iter;
					Renderer.iterations[pixelValue + 3 * width + 6] = iter;
					Renderer.iterations[pixelValue + 3 * width + 7] = iter;

					Renderer.iterations[pixelValue + 4 * width] = iter;
					Renderer.iterations[pixelValue + 4 * width + 1] = iter;
					Renderer.iterations[pixelValue + 4 * width + 2] = iter;
					Renderer.iterations[pixelValue + 4 * width + 3] = iter;
					Renderer.iterations[pixelValue + 4 * width + 4] = iter;
					Renderer.iterations[pixelValue + 4 * width + 5] = iter;
					Renderer.iterations[pixelValue + 4 * width + 6] = iter;
					Renderer.iterations[pixelValue + 4 * width + 7] = iter;

					Renderer.iterations[pixelValue + 5 * width] = iter;
					Renderer.iterations[pixelValue + 5 * width + 1] = iter;
					Renderer.iterations[pixelValue + 5 * width + 2] = iter;
					Renderer.iterations[pixelValue + 5 * width + 3] = iter;
					Renderer.iterations[pixelValue + 5 * width + 4] = iter;
					Renderer.iterations[pixelValue + 5 * width + 5] = iter;
					Renderer.iterations[pixelValue + 5 * width + 6] = iter;
					Renderer.iterations[pixelValue + 5 * width + 7] = iter;

					Renderer.iterations[pixelValue + 6 * width] = iter;
					Renderer.iterations[pixelValue + 6 * width + 1] = iter;
					Renderer.iterations[pixelValue + 6 * width + 2] = iter;
					Renderer.iterations[pixelValue + 6 * width + 3] = iter;
					Renderer.iterations[pixelValue + 6 * width + 4] = iter;
					Renderer.iterations[pixelValue + 6 * width + 5] = iter;
					Renderer.iterations[pixelValue + 6 * width + 6] = iter;
					Renderer.iterations[pixelValue + 6 * width + 7] = iter;

					Renderer.iterations[pixelValue + 7 * width] = iter;
					Renderer.iterations[pixelValue + 7 * width + 1] = iter;
					Renderer.iterations[pixelValue + 7 * width + 2] = iter;
					Renderer.iterations[pixelValue + 7 * width + 3] = iter;
					Renderer.iterations[pixelValue + 7 * width + 4] = iter;
					Renderer.iterations[pixelValue + 7 * width + 5] = iter;
					Renderer.iterations[pixelValue + 7 * width + 6] = iter;
					Renderer.iterations[pixelValue + 7 * width + 7] = iter;
					break;
				case 4:
					Renderer.pixels[pixelValue] = color;
					Renderer.pixels[pixelValue + 1] = color;
					Renderer.pixels[pixelValue + 2] = color;
					Renderer.pixels[pixelValue + 3] = color;
					Renderer.pixels[pixelValue + 4] = color;
					Renderer.pixels[pixelValue + 5] = color;
					Renderer.pixels[pixelValue + 6] = color;
					Renderer.pixels[pixelValue + 7] = color;
					Renderer.pixels[pixelValue + 8] = color;
					Renderer.pixels[pixelValue + 9] = color;
					Renderer.pixels[pixelValue + 10] = color;
					Renderer.pixels[pixelValue + 11] = color;
					Renderer.pixels[pixelValue + 12] = color;
					Renderer.pixels[pixelValue + 13] = color;
					Renderer.pixels[pixelValue + 14] = color;
					Renderer.pixels[pixelValue + 15] = color;

					Renderer.pixels[pixelValue + width] = color;
					Renderer.pixels[pixelValue + width + 1] = color;
					Renderer.pixels[pixelValue + width + 2] = color;
					Renderer.pixels[pixelValue + width + 3] = color;
					Renderer.pixels[pixelValue + width + 4] = color;
					Renderer.pixels[pixelValue + width + 5] = color;
					Renderer.pixels[pixelValue + width + 6] = color;
					Renderer.pixels[pixelValue + width + 7] = color;
					Renderer.pixels[pixelValue + width + 8] = color;
					Renderer.pixels[pixelValue + width + 9] = color;
					Renderer.pixels[pixelValue + width + 10] = color;
					Renderer.pixels[pixelValue + width + 11] = color;
					Renderer.pixels[pixelValue + width + 12] = color;
					Renderer.pixels[pixelValue + width + 13] = color;
					Renderer.pixels[pixelValue + width + 14] = color;
					Renderer.pixels[pixelValue + width + 15] = color;

					Renderer.pixels[pixelValue + 2 * width] = color;
					Renderer.pixels[pixelValue + 2 * width + 1] = color;
					Renderer.pixels[pixelValue + 2 * width + 2] = color;
					Renderer.pixels[pixelValue + 2 * width + 3] = color;
					Renderer.pixels[pixelValue + 2 * width + 4] = color;
					Renderer.pixels[pixelValue + 2 * width + 5] = color;
					Renderer.pixels[pixelValue + 2 * width + 6] = color;
					Renderer.pixels[pixelValue + 2 * width + 7] = color;
					Renderer.pixels[pixelValue + 2 * width + 8] = color;
					Renderer.pixels[pixelValue + 2 * width + 9] = color;
					Renderer.pixels[pixelValue + 2 * width + 10] = color;
					Renderer.pixels[pixelValue + 2 * width + 11] = color;
					Renderer.pixels[pixelValue + 2 * width + 12] = color;
					Renderer.pixels[pixelValue + 2 * width + 13] = color;
					Renderer.pixels[pixelValue + 2 * width + 14] = color;
					Renderer.pixels[pixelValue + 2 * width + 15] = color;

					Renderer.pixels[pixelValue + 3 * width] = color;
					Renderer.pixels[pixelValue + 3 * width + 1] = color;
					Renderer.pixels[pixelValue + 3 * width + 2] = color;
					Renderer.pixels[pixelValue + 3 * width + 3] = color;
					Renderer.pixels[pixelValue + 3 * width + 4] = color;
					Renderer.pixels[pixelValue + 3 * width + 5] = color;
					Renderer.pixels[pixelValue + 3 * width + 6] = color;
					Renderer.pixels[pixelValue + 3 * width + 7] = color;
					Renderer.pixels[pixelValue + 3 * width + 8] = color;
					Renderer.pixels[pixelValue + 3 * width + 9] = color;
					Renderer.pixels[pixelValue + 3 * width + 10] = color;
					Renderer.pixels[pixelValue + 3 * width + 11] = color;
					Renderer.pixels[pixelValue + 3 * width + 12] = color;
					Renderer.pixels[pixelValue + 3 * width + 13] = color;
					Renderer.pixels[pixelValue + 3 * width + 14] = color;
					Renderer.pixels[pixelValue + 3 * width + 15] = color;

					Renderer.pixels[pixelValue + 4 * width] = color;
					Renderer.pixels[pixelValue + 4 * width + 1] = color;
					Renderer.pixels[pixelValue + 4 * width + 2] = color;
					Renderer.pixels[pixelValue + 4 * width + 3] = color;
					Renderer.pixels[pixelValue + 4 * width + 4] = color;
					Renderer.pixels[pixelValue + 4 * width + 5] = color;
					Renderer.pixels[pixelValue + 4 * width + 6] = color;
					Renderer.pixels[pixelValue + 4 * width + 7] = color;
					Renderer.pixels[pixelValue + 4 * width + 8] = color;
					Renderer.pixels[pixelValue + 4 * width + 9] = color;
					Renderer.pixels[pixelValue + 4 * width + 10] = color;
					Renderer.pixels[pixelValue + 4 * width + 11] = color;
					Renderer.pixels[pixelValue + 4 * width + 12] = color;
					Renderer.pixels[pixelValue + 4 * width + 13] = color;
					Renderer.pixels[pixelValue + 4 * width + 14] = color;
					Renderer.pixels[pixelValue + 4 * width + 15] = color;

					Renderer.pixels[pixelValue + 5 * width] = color;
					Renderer.pixels[pixelValue + 5 * width + 1] = color;
					Renderer.pixels[pixelValue + 5 * width + 2] = color;
					Renderer.pixels[pixelValue + 5 * width + 3] = color;
					Renderer.pixels[pixelValue + 5 * width + 4] = color;
					Renderer.pixels[pixelValue + 5 * width + 5] = color;
					Renderer.pixels[pixelValue + 5 * width + 6] = color;
					Renderer.pixels[pixelValue + 5 * width + 7] = color;
					Renderer.pixels[pixelValue + 5 * width + 8] = color;
					Renderer.pixels[pixelValue + 5 * width + 9] = color;
					Renderer.pixels[pixelValue + 5 * width + 10] = color;
					Renderer.pixels[pixelValue + 5 * width + 11] = color;
					Renderer.pixels[pixelValue + 5 * width + 12] = color;
					Renderer.pixels[pixelValue + 5 * width + 13] = color;
					Renderer.pixels[pixelValue + 5 * width + 14] = color;
					Renderer.pixels[pixelValue + 5 * width + 15] = color;

					Renderer.pixels[pixelValue + 6 * width] = color;
					Renderer.pixels[pixelValue + 6 * width + 1] = color;
					Renderer.pixels[pixelValue + 6 * width + 2] = color;
					Renderer.pixels[pixelValue + 6 * width + 3] = color;
					Renderer.pixels[pixelValue + 6 * width + 4] = color;
					Renderer.pixels[pixelValue + 6 * width + 5] = color;
					Renderer.pixels[pixelValue + 6 * width + 6] = color;
					Renderer.pixels[pixelValue + 6 * width + 7] = color;
					Renderer.pixels[pixelValue + 6 * width + 8] = color;
					Renderer.pixels[pixelValue + 6 * width + 9] = color;
					Renderer.pixels[pixelValue + 6 * width + 10] = color;
					Renderer.pixels[pixelValue + 6 * width + 11] = color;
					Renderer.pixels[pixelValue + 6 * width + 12] = color;
					Renderer.pixels[pixelValue + 6 * width + 13] = color;
					Renderer.pixels[pixelValue + 6 * width + 14] = color;
					Renderer.pixels[pixelValue + 6 * width + 15] = color;

					Renderer.pixels[pixelValue + 7 * width] = color;
					Renderer.pixels[pixelValue + 7 * width + 1] = color;
					Renderer.pixels[pixelValue + 7 * width + 2] = color;
					Renderer.pixels[pixelValue + 7 * width + 3] = color;
					Renderer.pixels[pixelValue + 7 * width + 4] = color;
					Renderer.pixels[pixelValue + 7 * width + 5] = color;
					Renderer.pixels[pixelValue + 7 * width + 6] = color;
					Renderer.pixels[pixelValue + 7 * width + 7] = color;
					Renderer.pixels[pixelValue + 7 * width + 8] = color;
					Renderer.pixels[pixelValue + 7 * width + 9] = color;
					Renderer.pixels[pixelValue + 7 * width + 10] = color;
					Renderer.pixels[pixelValue + 7 * width + 11] = color;
					Renderer.pixels[pixelValue + 7 * width + 12] = color;
					Renderer.pixels[pixelValue + 7 * width + 13] = color;
					Renderer.pixels[pixelValue + 7 * width + 14] = color;
					Renderer.pixels[pixelValue + 7 * width + 15] = color;

					Renderer.pixels[pixelValue + 8 * width] = color;
					Renderer.pixels[pixelValue + 8 * width + 1] = color;
					Renderer.pixels[pixelValue + 8 * width + 2] = color;
					Renderer.pixels[pixelValue + 8 * width + 3] = color;
					Renderer.pixels[pixelValue + 8 * width + 4] = color;
					Renderer.pixels[pixelValue + 8 * width + 5] = color;
					Renderer.pixels[pixelValue + 8 * width + 6] = color;
					Renderer.pixels[pixelValue + 8 * width + 7] = color;
					Renderer.pixels[pixelValue + 8 * width + 8] = color;
					Renderer.pixels[pixelValue + 8 * width + 9] = color;
					Renderer.pixels[pixelValue + 8 * width + 10] = color;
					Renderer.pixels[pixelValue + 8 * width + 11] = color;
					Renderer.pixels[pixelValue + 8 * width + 12] = color;
					Renderer.pixels[pixelValue + 8 * width + 13] = color;
					Renderer.pixels[pixelValue + 8 * width + 14] = color;
					Renderer.pixels[pixelValue + 8 * width + 15] = color;

					Renderer.pixels[pixelValue + 9 * width] = color;
					Renderer.pixels[pixelValue + 9 * width + 1] = color;
					Renderer.pixels[pixelValue + 9 * width + 2] = color;
					Renderer.pixels[pixelValue + 9 * width + 3] = color;
					Renderer.pixels[pixelValue + 9 * width + 4] = color;
					Renderer.pixels[pixelValue + 9 * width + 5] = color;
					Renderer.pixels[pixelValue + 9 * width + 6] = color;
					Renderer.pixels[pixelValue + 9 * width + 7] = color;
					Renderer.pixels[pixelValue + 9 * width + 8] = color;
					Renderer.pixels[pixelValue + 9 * width + 9] = color;
					Renderer.pixels[pixelValue + 9 * width + 10] = color;
					Renderer.pixels[pixelValue + 9 * width + 11] = color;
					Renderer.pixels[pixelValue + 9 * width + 12] = color;
					Renderer.pixels[pixelValue + 9 * width + 13] = color;
					Renderer.pixels[pixelValue + 9 * width + 14] = color;
					Renderer.pixels[pixelValue + 9 * width + 15] = color;

					Renderer.pixels[pixelValue + 10 * width] = color;
					Renderer.pixels[pixelValue + 10 * width + 1] = color;
					Renderer.pixels[pixelValue + 10 * width + 2] = color;
					Renderer.pixels[pixelValue + 10 * width + 3] = color;
					Renderer.pixels[pixelValue + 10 * width + 4] = color;
					Renderer.pixels[pixelValue + 10 * width + 5] = color;
					Renderer.pixels[pixelValue + 10 * width + 6] = color;
					Renderer.pixels[pixelValue + 10 * width + 7] = color;
					Renderer.pixels[pixelValue + 10 * width + 8] = color;
					Renderer.pixels[pixelValue + 10 * width + 9] = color;
					Renderer.pixels[pixelValue + 10 * width + 10] = color;
					Renderer.pixels[pixelValue + 10 * width + 11] = color;
					Renderer.pixels[pixelValue + 10 * width + 12] = color;
					Renderer.pixels[pixelValue + 10 * width + 13] = color;
					Renderer.pixels[pixelValue + 10 * width + 14] = color;
					Renderer.pixels[pixelValue + 10 * width + 15] = color;

					Renderer.pixels[pixelValue + 11 * width] = color;
					Renderer.pixels[pixelValue + 11 * width + 1] = color;
					Renderer.pixels[pixelValue + 11 * width + 2] = color;
					Renderer.pixels[pixelValue + 11 * width + 3] = color;
					Renderer.pixels[pixelValue + 11 * width + 4] = color;
					Renderer.pixels[pixelValue + 11 * width + 5] = color;
					Renderer.pixels[pixelValue + 11 * width + 6] = color;
					Renderer.pixels[pixelValue + 11 * width + 7] = color;
					Renderer.pixels[pixelValue + 11 * width + 8] = color;
					Renderer.pixels[pixelValue + 11 * width + 9] = color;
					Renderer.pixels[pixelValue + 11 * width + 10] = color;
					Renderer.pixels[pixelValue + 11 * width + 11] = color;
					Renderer.pixels[pixelValue + 11 * width + 12] = color;
					Renderer.pixels[pixelValue + 11 * width + 13] = color;
					Renderer.pixels[pixelValue + 11 * width + 14] = color;
					Renderer.pixels[pixelValue + 11 * width + 15] = color;

					Renderer.pixels[pixelValue + 12 * width] = color;
					Renderer.pixels[pixelValue + 12 * width + 1] = color;
					Renderer.pixels[pixelValue + 12 * width + 2] = color;
					Renderer.pixels[pixelValue + 12 * width + 3] = color;
					Renderer.pixels[pixelValue + 12 * width + 4] = color;
					Renderer.pixels[pixelValue + 12 * width + 5] = color;
					Renderer.pixels[pixelValue + 12 * width + 6] = color;
					Renderer.pixels[pixelValue + 12 * width + 7] = color;
					Renderer.pixels[pixelValue + 12 * width + 8] = color;
					Renderer.pixels[pixelValue + 12 * width + 9] = color;
					Renderer.pixels[pixelValue + 12 * width + 10] = color;
					Renderer.pixels[pixelValue + 12 * width + 11] = color;
					Renderer.pixels[pixelValue + 12 * width + 12] = color;
					Renderer.pixels[pixelValue + 12 * width + 13] = color;
					Renderer.pixels[pixelValue + 12 * width + 14] = color;
					Renderer.pixels[pixelValue + 12 * width + 15] = color;

					Renderer.pixels[pixelValue + 13 * width] = color;
					Renderer.pixels[pixelValue + 13 * width + 1] = color;
					Renderer.pixels[pixelValue + 13 * width + 2] = color;
					Renderer.pixels[pixelValue + 13 * width + 3] = color;
					Renderer.pixels[pixelValue + 13 * width + 4] = color;
					Renderer.pixels[pixelValue + 13 * width + 5] = color;
					Renderer.pixels[pixelValue + 13 * width + 6] = color;
					Renderer.pixels[pixelValue + 13 * width + 7] = color;
					Renderer.pixels[pixelValue + 13 * width + 8] = color;
					Renderer.pixels[pixelValue + 13 * width + 9] = color;
					Renderer.pixels[pixelValue + 13 * width + 10] = color;
					Renderer.pixels[pixelValue + 13 * width + 11] = color;
					Renderer.pixels[pixelValue + 13 * width + 12] = color;
					Renderer.pixels[pixelValue + 13 * width + 13] = color;
					Renderer.pixels[pixelValue + 13 * width + 14] = color;
					Renderer.pixels[pixelValue + 13 * width + 15] = color;

					Renderer.pixels[pixelValue + 14 * width] = color;
					Renderer.pixels[pixelValue + 14 * width + 1] = color;
					Renderer.pixels[pixelValue + 14 * width + 2] = color;
					Renderer.pixels[pixelValue + 14 * width + 3] = color;
					Renderer.pixels[pixelValue + 14 * width + 4] = color;
					Renderer.pixels[pixelValue + 14 * width + 5] = color;
					Renderer.pixels[pixelValue + 14 * width + 6] = color;
					Renderer.pixels[pixelValue + 14 * width + 7] = color;
					Renderer.pixels[pixelValue + 14 * width + 8] = color;
					Renderer.pixels[pixelValue + 14 * width + 9] = color;
					Renderer.pixels[pixelValue + 14 * width + 10] = color;
					Renderer.pixels[pixelValue + 14 * width + 11] = color;
					Renderer.pixels[pixelValue + 14 * width + 12] = color;
					Renderer.pixels[pixelValue + 14 * width + 13] = color;
					Renderer.pixels[pixelValue + 14 * width + 14] = color;
					Renderer.pixels[pixelValue + 14 * width + 15] = color;

					Renderer.pixels[pixelValue + 15 * width] = color;
					Renderer.pixels[pixelValue + 15 * width + 1] = color;
					Renderer.pixels[pixelValue + 15 * width + 2] = color;
					Renderer.pixels[pixelValue + 15 * width + 3] = color;
					Renderer.pixels[pixelValue + 15 * width + 4] = color;
					Renderer.pixels[pixelValue + 15 * width + 5] = color;
					Renderer.pixels[pixelValue + 15 * width + 6] = color;
					Renderer.pixels[pixelValue + 15 * width + 7] = color;
					Renderer.pixels[pixelValue + 15 * width + 8] = color;
					Renderer.pixels[pixelValue + 15 * width + 9] = color;
					Renderer.pixels[pixelValue + 15 * width + 10] = color;
					Renderer.pixels[pixelValue + 15 * width + 11] = color;
					Renderer.pixels[pixelValue + 15 * width + 12] = color;
					Renderer.pixels[pixelValue + 15 * width + 13] = color;
					Renderer.pixels[pixelValue + 15 * width + 14] = color;
					Renderer.pixels[pixelValue + 15 * width + 15] = color;

					Renderer.iterations[pixelValue] = iter;
					Renderer.iterations[pixelValue + 1] = iter;
					Renderer.iterations[pixelValue + 2] = iter;
					Renderer.iterations[pixelValue + 3] = iter;
					Renderer.iterations[pixelValue + 4] = iter;
					Renderer.iterations[pixelValue + 5] = iter;
					Renderer.iterations[pixelValue + 6] = iter;
					Renderer.iterations[pixelValue + 7] = iter;
					Renderer.iterations[pixelValue + 8] = iter;
					Renderer.iterations[pixelValue + 9] = iter;
					Renderer.iterations[pixelValue + 10] = iter;
					Renderer.iterations[pixelValue + 11] = iter;
					Renderer.iterations[pixelValue + 12] = iter;
					Renderer.iterations[pixelValue + 13] = iter;
					Renderer.iterations[pixelValue + 14] = iter;
					Renderer.iterations[pixelValue + 15] = iter;

					Renderer.iterations[pixelValue + width] = iter;
					Renderer.iterations[pixelValue + width + 1] = iter;
					Renderer.iterations[pixelValue + width + 2] = iter;
					Renderer.iterations[pixelValue + width + 3] = iter;
					Renderer.iterations[pixelValue + width + 4] = iter;
					Renderer.iterations[pixelValue + width + 5] = iter;
					Renderer.iterations[pixelValue + width + 6] = iter;
					Renderer.iterations[pixelValue + width + 7] = iter;
					Renderer.iterations[pixelValue + width + 8] = iter;
					Renderer.iterations[pixelValue + width + 9] = iter;
					Renderer.iterations[pixelValue + width + 10] = iter;
					Renderer.iterations[pixelValue + width + 11] = iter;
					Renderer.iterations[pixelValue + width + 12] = iter;
					Renderer.iterations[pixelValue + width + 13] = iter;
					Renderer.iterations[pixelValue + width + 14] = iter;
					Renderer.iterations[pixelValue + width + 15] = iter;

					Renderer.iterations[pixelValue + 2 * width] = iter;
					Renderer.iterations[pixelValue + 2 * width + 1] = iter;
					Renderer.iterations[pixelValue + 2 * width + 2] = iter;
					Renderer.iterations[pixelValue + 2 * width + 3] = iter;
					Renderer.iterations[pixelValue + 2 * width + 4] = iter;
					Renderer.iterations[pixelValue + 2 * width + 5] = iter;
					Renderer.iterations[pixelValue + 2 * width + 6] = iter;
					Renderer.iterations[pixelValue + 2 * width + 7] = iter;
					Renderer.iterations[pixelValue + 2 * width + 8] = iter;
					Renderer.iterations[pixelValue + 2 * width + 9] = iter;
					Renderer.iterations[pixelValue + 2 * width + 10] = iter;
					Renderer.iterations[pixelValue + 2 * width + 11] = iter;
					Renderer.iterations[pixelValue + 2 * width + 12] = iter;
					Renderer.iterations[pixelValue + 2 * width + 13] = iter;
					Renderer.iterations[pixelValue + 2 * width + 14] = iter;
					Renderer.iterations[pixelValue + 2 * width + 15] = iter;

					Renderer.iterations[pixelValue + 3 * width] = iter;
					Renderer.iterations[pixelValue + 3 * width + 1] = iter;
					Renderer.iterations[pixelValue + 3 * width + 2] = iter;
					Renderer.iterations[pixelValue + 3 * width + 3] = iter;
					Renderer.iterations[pixelValue + 3 * width + 4] = iter;
					Renderer.iterations[pixelValue + 3 * width + 5] = iter;
					Renderer.iterations[pixelValue + 3 * width + 6] = iter;
					Renderer.iterations[pixelValue + 3 * width + 7] = iter;
					Renderer.iterations[pixelValue + 3 * width + 8] = iter;
					Renderer.iterations[pixelValue + 3 * width + 9] = iter;
					Renderer.iterations[pixelValue + 3 * width + 10] = iter;
					Renderer.iterations[pixelValue + 3 * width + 11] = iter;
					Renderer.iterations[pixelValue + 3 * width + 12] = iter;
					Renderer.iterations[pixelValue + 3 * width + 13] = iter;
					Renderer.iterations[pixelValue + 3 * width + 14] = iter;
					Renderer.iterations[pixelValue + 3 * width + 15] = iter;

					Renderer.iterations[pixelValue + 4 * width] = iter;
					Renderer.iterations[pixelValue + 4 * width + 1] = iter;
					Renderer.iterations[pixelValue + 4 * width + 2] = iter;
					Renderer.iterations[pixelValue + 4 * width + 3] = iter;
					Renderer.iterations[pixelValue + 4 * width + 4] = iter;
					Renderer.iterations[pixelValue + 4 * width + 5] = iter;
					Renderer.iterations[pixelValue + 4 * width + 6] = iter;
					Renderer.iterations[pixelValue + 4 * width + 7] = iter;
					Renderer.iterations[pixelValue + 4 * width + 8] = iter;
					Renderer.iterations[pixelValue + 4 * width + 9] = iter;
					Renderer.iterations[pixelValue + 4 * width + 10] = iter;
					Renderer.iterations[pixelValue + 4 * width + 11] = iter;
					Renderer.iterations[pixelValue + 4 * width + 12] = iter;
					Renderer.iterations[pixelValue + 4 * width + 13] = iter;
					Renderer.iterations[pixelValue + 4 * width + 14] = iter;
					Renderer.iterations[pixelValue + 4 * width + 15] = iter;

					Renderer.iterations[pixelValue + 5 * width] = iter;
					Renderer.iterations[pixelValue + 5 * width + 1] = iter;
					Renderer.iterations[pixelValue + 5 * width + 2] = iter;
					Renderer.iterations[pixelValue + 5 * width + 3] = iter;
					Renderer.iterations[pixelValue + 5 * width + 4] = iter;
					Renderer.iterations[pixelValue + 5 * width + 5] = iter;
					Renderer.iterations[pixelValue + 5 * width + 6] = iter;
					Renderer.iterations[pixelValue + 5 * width + 7] = iter;
					Renderer.iterations[pixelValue + 5 * width + 8] = iter;
					Renderer.iterations[pixelValue + 5 * width + 9] = iter;
					Renderer.iterations[pixelValue + 5 * width + 10] = iter;
					Renderer.iterations[pixelValue + 5 * width + 11] = iter;
					Renderer.iterations[pixelValue + 5 * width + 12] = iter;
					Renderer.iterations[pixelValue + 5 * width + 13] = iter;
					Renderer.iterations[pixelValue + 5 * width + 14] = iter;
					Renderer.iterations[pixelValue + 5 * width + 15] = iter;

					Renderer.iterations[pixelValue + 6 * width] = iter;
					Renderer.iterations[pixelValue + 6 * width + 1] = iter;
					Renderer.iterations[pixelValue + 6 * width + 2] = iter;
					Renderer.iterations[pixelValue + 6 * width + 3] = iter;
					Renderer.iterations[pixelValue + 6 * width + 4] = iter;
					Renderer.iterations[pixelValue + 6 * width + 5] = iter;
					Renderer.iterations[pixelValue + 6 * width + 6] = iter;
					Renderer.iterations[pixelValue + 6 * width + 7] = iter;
					Renderer.iterations[pixelValue + 6 * width + 8] = iter;
					Renderer.iterations[pixelValue + 6 * width + 9] = iter;
					Renderer.iterations[pixelValue + 6 * width + 10] = iter;
					Renderer.iterations[pixelValue + 6 * width + 11] = iter;
					Renderer.iterations[pixelValue + 6 * width + 12] = iter;
					Renderer.iterations[pixelValue + 6 * width + 13] = iter;
					Renderer.iterations[pixelValue + 6 * width + 14] = iter;
					Renderer.iterations[pixelValue + 6 * width + 15] = iter;

					Renderer.iterations[pixelValue + 7 * width] = iter;
					Renderer.iterations[pixelValue + 7 * width + 1] = iter;
					Renderer.iterations[pixelValue + 7 * width + 2] = iter;
					Renderer.iterations[pixelValue + 7 * width + 3] = iter;
					Renderer.iterations[pixelValue + 7 * width + 4] = iter;
					Renderer.iterations[pixelValue + 7 * width + 5] = iter;
					Renderer.iterations[pixelValue + 7 * width + 6] = iter;
					Renderer.iterations[pixelValue + 7 * width + 7] = iter;
					Renderer.iterations[pixelValue + 7 * width + 8] = iter;
					Renderer.iterations[pixelValue + 7 * width + 9] = iter;
					Renderer.iterations[pixelValue + 7 * width + 10] = iter;
					Renderer.iterations[pixelValue + 7 * width + 11] = iter;
					Renderer.iterations[pixelValue + 7 * width + 12] = iter;
					Renderer.iterations[pixelValue + 7 * width + 13] = iter;
					Renderer.iterations[pixelValue + 7 * width + 14] = iter;
					Renderer.iterations[pixelValue + 7 * width + 15] = iter;

					Renderer.iterations[pixelValue + 8 * width] = iter;
					Renderer.iterations[pixelValue + 8 * width + 1] = iter;
					Renderer.iterations[pixelValue + 8 * width + 2] = iter;
					Renderer.iterations[pixelValue + 8 * width + 3] = iter;
					Renderer.iterations[pixelValue + 8 * width + 4] = iter;
					Renderer.iterations[pixelValue + 8 * width + 5] = iter;
					Renderer.iterations[pixelValue + 8 * width + 6] = iter;
					Renderer.iterations[pixelValue + 8 * width + 7] = iter;
					Renderer.iterations[pixelValue + 8 * width + 8] = iter;
					Renderer.iterations[pixelValue + 8 * width + 9] = iter;
					Renderer.iterations[pixelValue + 8 * width + 10] = iter;
					Renderer.iterations[pixelValue + 8 * width + 11] = iter;
					Renderer.iterations[pixelValue + 8 * width + 12] = iter;
					Renderer.iterations[pixelValue + 8 * width + 13] = iter;
					Renderer.iterations[pixelValue + 8 * width + 14] = iter;
					Renderer.iterations[pixelValue + 8 * width + 15] = iter;

					Renderer.iterations[pixelValue + 9 * width] = iter;
					Renderer.iterations[pixelValue + 9 * width + 1] = iter;
					Renderer.iterations[pixelValue + 9 * width + 2] = iter;
					Renderer.iterations[pixelValue + 9 * width + 3] = iter;
					Renderer.iterations[pixelValue + 9 * width + 4] = iter;
					Renderer.iterations[pixelValue + 9 * width + 5] = iter;
					Renderer.iterations[pixelValue + 9 * width + 6] = iter;
					Renderer.iterations[pixelValue + 9 * width + 7] = iter;
					Renderer.iterations[pixelValue + 9 * width + 8] = iter;
					Renderer.iterations[pixelValue + 9 * width + 9] = iter;
					Renderer.iterations[pixelValue + 9 * width + 10] = iter;
					Renderer.iterations[pixelValue + 9 * width + 11] = iter;
					Renderer.iterations[pixelValue + 9 * width + 12] = iter;
					Renderer.iterations[pixelValue + 9 * width + 13] = iter;
					Renderer.iterations[pixelValue + 9 * width + 14] = iter;
					Renderer.iterations[pixelValue + 9 * width + 15] = iter;

					Renderer.iterations[pixelValue + 10 * width] = iter;
					Renderer.iterations[pixelValue + 10 * width + 1] = iter;
					Renderer.iterations[pixelValue + 10 * width + 2] = iter;
					Renderer.iterations[pixelValue + 10 * width + 3] = iter;
					Renderer.iterations[pixelValue + 10 * width + 4] = iter;
					Renderer.iterations[pixelValue + 10 * width + 5] = iter;
					Renderer.iterations[pixelValue + 10 * width + 6] = iter;
					Renderer.iterations[pixelValue + 10 * width + 7] = iter;
					Renderer.iterations[pixelValue + 10 * width + 8] = iter;
					Renderer.iterations[pixelValue + 10 * width + 9] = iter;
					Renderer.iterations[pixelValue + 10 * width + 10] = iter;
					Renderer.iterations[pixelValue + 10 * width + 11] = iter;
					Renderer.iterations[pixelValue + 10 * width + 12] = iter;
					Renderer.iterations[pixelValue + 10 * width + 13] = iter;
					Renderer.iterations[pixelValue + 10 * width + 14] = iter;
					Renderer.iterations[pixelValue + 10 * width + 15] = iter;

					Renderer.iterations[pixelValue + 11 * width] = iter;
					Renderer.iterations[pixelValue + 11 * width + 1] = iter;
					Renderer.iterations[pixelValue + 11 * width + 2] = iter;
					Renderer.iterations[pixelValue + 11 * width + 3] = iter;
					Renderer.iterations[pixelValue + 11 * width + 4] = iter;
					Renderer.iterations[pixelValue + 11 * width + 5] = iter;
					Renderer.iterations[pixelValue + 11 * width + 6] = iter;
					Renderer.iterations[pixelValue + 11 * width + 7] = iter;
					Renderer.iterations[pixelValue + 11 * width + 8] = iter;
					Renderer.iterations[pixelValue + 11 * width + 9] = iter;
					Renderer.iterations[pixelValue + 11 * width + 10] = iter;
					Renderer.iterations[pixelValue + 11 * width + 11] = iter;
					Renderer.iterations[pixelValue + 11 * width + 12] = iter;
					Renderer.iterations[pixelValue + 11 * width + 13] = iter;
					Renderer.iterations[pixelValue + 11 * width + 14] = iter;
					Renderer.iterations[pixelValue + 11 * width + 15] = iter;

					Renderer.iterations[pixelValue + 12 * width] = iter;
					Renderer.iterations[pixelValue + 12 * width + 1] = iter;
					Renderer.iterations[pixelValue + 12 * width + 2] = iter;
					Renderer.iterations[pixelValue + 12 * width + 3] = iter;
					Renderer.iterations[pixelValue + 12 * width + 4] = iter;
					Renderer.iterations[pixelValue + 12 * width + 5] = iter;
					Renderer.iterations[pixelValue + 12 * width + 6] = iter;
					Renderer.iterations[pixelValue + 12 * width + 7] = iter;
					Renderer.iterations[pixelValue + 12 * width + 8] = iter;
					Renderer.iterations[pixelValue + 12 * width + 9] = iter;
					Renderer.iterations[pixelValue + 12 * width + 10] = iter;
					Renderer.iterations[pixelValue + 12 * width + 11] = iter;
					Renderer.iterations[pixelValue + 12 * width + 12] = iter;
					Renderer.iterations[pixelValue + 12 * width + 13] = iter;
					Renderer.iterations[pixelValue + 12 * width + 14] = iter;
					Renderer.iterations[pixelValue + 12 * width + 15] = iter;

					Renderer.iterations[pixelValue + 13 * width] = iter;
					Renderer.iterations[pixelValue + 13 * width + 1] = iter;
					Renderer.iterations[pixelValue + 13 * width + 2] = iter;
					Renderer.iterations[pixelValue + 13 * width + 3] = iter;
					Renderer.iterations[pixelValue + 13 * width + 4] = iter;
					Renderer.iterations[pixelValue + 13 * width + 5] = iter;
					Renderer.iterations[pixelValue + 13 * width + 6] = iter;
					Renderer.iterations[pixelValue + 13 * width + 7] = iter;
					Renderer.iterations[pixelValue + 13 * width + 8] = iter;
					Renderer.iterations[pixelValue + 13 * width + 9] = iter;
					Renderer.iterations[pixelValue + 13 * width + 10] = iter;
					Renderer.iterations[pixelValue + 13 * width + 11] = iter;
					Renderer.iterations[pixelValue + 13 * width + 12] = iter;
					Renderer.iterations[pixelValue + 13 * width + 13] = iter;
					Renderer.iterations[pixelValue + 13 * width + 14] = iter;
					Renderer.iterations[pixelValue + 13 * width + 15] = iter;

					Renderer.iterations[pixelValue + 14 * width] = iter;
					Renderer.iterations[pixelValue + 14 * width + 1] = iter;
					Renderer.iterations[pixelValue + 14 * width + 2] = iter;
					Renderer.iterations[pixelValue + 14 * width + 3] = iter;
					Renderer.iterations[pixelValue + 14 * width + 4] = iter;
					Renderer.iterations[pixelValue + 14 * width + 5] = iter;
					Renderer.iterations[pixelValue + 14 * width + 6] = iter;
					Renderer.iterations[pixelValue + 14 * width + 7] = iter;
					Renderer.iterations[pixelValue + 14 * width + 8] = iter;
					Renderer.iterations[pixelValue + 14 * width + 9] = iter;
					Renderer.iterations[pixelValue + 14 * width + 10] = iter;
					Renderer.iterations[pixelValue + 14 * width + 11] = iter;
					Renderer.iterations[pixelValue + 14 * width + 12] = iter;
					Renderer.iterations[pixelValue + 14 * width + 13] = iter;
					Renderer.iterations[pixelValue + 14 * width + 14] = iter;
					Renderer.iterations[pixelValue + 14 * width + 15] = iter;

					Renderer.iterations[pixelValue + 15 * width] = iter;
					Renderer.iterations[pixelValue + 15 * width + 1] = iter;
					Renderer.iterations[pixelValue + 15 * width + 2] = iter;
					Renderer.iterations[pixelValue + 15 * width + 3] = iter;
					Renderer.iterations[pixelValue + 15 * width + 4] = iter;
					Renderer.iterations[pixelValue + 15 * width + 5] = iter;
					Renderer.iterations[pixelValue + 15 * width + 6] = iter;
					Renderer.iterations[pixelValue + 15 * width + 7] = iter;
					Renderer.iterations[pixelValue + 15 * width + 8] = iter;
					Renderer.iterations[pixelValue + 15 * width + 9] = iter;
					Renderer.iterations[pixelValue + 15 * width + 10] = iter;
					Renderer.iterations[pixelValue + 15 * width + 11] = iter;
					Renderer.iterations[pixelValue + 15 * width + 12] = iter;
					Renderer.iterations[pixelValue + 15 * width + 13] = iter;
					Renderer.iterations[pixelValue + 15 * width + 14] = iter;
					Renderer.iterations[pixelValue + 15 * width + 15] = iter;
					break;
				}
			} catch (Exception) { }
		}
	}
}
